dctb-mysql:
  container_name: dctb-mysql
  image: mysql:5.7
  volumes:
    - "./mysql:/var/lib/mysql"
  environment:
    MYSQL_ROOT_PASSWORD : root
    MYSQL_DATABASE      : base
    MYSQL_USER          : dctb-root
    MYSQL_PASSWORD      : dctb-root
dctb-phpmyadmin:
  container_name: dctb-phpmyadmin
  image: phpmyadmin/phpmyadmin
  links:
    - dctb-mysql:db
  ports:
    - "9999:80"
dctb-php7:
  container_name: dctb-php7
  image: diogocezar/dctb-docker-php7
  volumes:
    - "./www:/var/www"
  links:
    - dctb-mysql
  ports:
    - "8888:80"
    - "2222:22"